services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - .:/app
      - /app/node_modules
      - /app/prisma
    ports:
      - 4040:4040
      - 9229:9229
    command: npm run start
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: always


volumes:
  pgdata: